### ISSUE TITLE
Softlock with Jolly Co-Op Mod when using alt autosleep

### ISSUE THREAD

**Issue by SemonS1500** [thalber/BetterShelters#2]
When one of cats is dead game stops closing doors in shelters what makes a softlock when one of cats dies (even if cat isnt in the shelter, RIP easy mod).
If i may ask can you make so death state counts as lying donw?

**Comment by thalber** [comment]
Will come with the last BSH update

**Comment by SemonS1500** [comment]
Also i just played and noticed that even if alt autosleep is off its still softlocks you. (Unless you need to restart the game after changing setting, because i didnt.)

**Comment by Dual-Iron** [comment]
Bump. Seems like the method `BetterShelters.Door_Close_Hook` could check if a player is conscious before prematurely returning to fix this bug.

**Comment by thalber** [comment]
should be fixed in 1.3
https://github.com/thalber/BetterShelters/releases/tag/1.3
